server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: aluno-service
          uri: lb://aluno-service
          predicates:
            - Path=/api/v1/alunos/**

        - id: disciplina-service
          uri: lb://disciplina-service
          predicates:
            - Path=/api/v1/disciplinas/**

        - id: matricula-service
          uri: lb://matricula-service
          predicates:
            - Path=/api/v1/matriculas/**

        - id: avaliacao-service
          uri: lb://avaliacao-service
          predicates:
            - Path=/api/v1/avaliacoes/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"