version: '3.8'

services:
  aluno-service:
    build: ./services/aluno-service
    container_name: aluno-service
    ports:
      - "8081:8081"
    networks:
      - tac-network

  disciplina-service:
    build: ./services/disciplina-service
    container_name: disciplina-service
    ports:
      - "8082:8082"
    networks:
      - tac-network

  matricula-service:
    build: ./services/matricula-service
    container_name: matricula-service
    ports:
      - "8083:8083"
    networks:
      - tac-network

  avaliacao-service:
    build: ./services/avaliacao-service
    container_name: avaliacao-service
    ports:
      - "8084:8084"
    networks:
      - tac-network

  gateway:
    build: ./services/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - aluno-service
      - disciplina-service
      - matricula-service
      - avaliacao-service
    networks:
      - tac-network

networks:
  tac-network:
    driver: bridge
