sonar.projectName=Tac-Projetofim
sonar.sourceEncoding=UTF-8


sonar.sources=services/aluno-service/src/main/java,services/disciplina-service/src/main/java,services/matricula-service/src/main/java,services/avaliacao-service/src/main/java,services/gateway/src/main/java,services/notificacoes/src/main/java,frontend/src


sonar.tests=services/aluno-service/src/test,services/disciplina-service/src/test,services/matricula-service/src/test,services/avaliacao-service/src/test

sonar.java.binaries=services/aluno-service/target/classes,services/disciplina-service/target/classes,services/matricula-service/target/classes,services/avaliacao-service/target/classes,services/gateway/target/classes,services/notificacoes/target/classes,services/contracts/target/classes
sonar.coverage.jacoco.xmlReportPaths=services/aluno-service/target/site/jacoco/jacoco.xml,services/disciplina-service/target/site/jacoco/jacoco.xml,services/matricula-service/target/site/jacoco/jacoco.xml,services/avaliacao-service/target/site/jacoco/jacoco.xml,services/gateway/target/site/jacoco/jacoco.xml,services/notificacoes/target/site/jacoco/jacoco.xml


sonar.exclusions=**/target/**,**/.idea/**,**/.git/**,docker/**,docs/**,**/src/test/resources/**/*
sonar.coverage.exclusions=frontend/**,services/contracts/**,services/observability-common/**,**/*Application.java,**/config/**,**/dto/**,**/event/**,**/mensageria/**,**/producer/**
sonar.cpd.exclusions=**/mensageria/events/**,**/event/**