# Server Configuration
server.port=8083

# Swagger UI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# H2 Database Configuration (in-memory)
spring.datasource.url=jdbc:h2:mem:matriculadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Comunicação inter-serviços (Docker-friendly)
services.aluno.base-url=http://aluno-service:8081/api/v1/alunos
services.disciplina.base-url=http://disciplina-service:8082/api/v1/disciplinas
