server:
  port: 8081

spring:
  application:
    name: notificacoes
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672
    virtual-host: /
  datasource:
    url: jdbc:h2:mem:notificacoes;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
