server:
  port: 8081

spring:
  application:
    name: notificacoes

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    port: 5672
    virtual-host: /

  datasource:
    url: jdbc:postgresql://postgres:5432/tac_notificacoes
    driver-class-name: org.postgresql.Driver
    username: tac
    password: tac
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true



  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] %logger{36} traceId=%X{traceId:-} spanId=%X{spanId:-} - %msg%n"

# Observabilidade (Actuator + Prometheus + Tracing Brave)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "never"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

